[package]
name = "lyrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = {version = "*"}
clap = {version = "*", features = ["derive"]}
bunt = {version = "*"}
reqwest = {version = "*"}
serde = {version = "*", features = ["derive"]}
serde_json = {version = "*"}
tokio = {version = "*", features = ["full"]}